ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "birthday" DATE,
  ADD COLUMN IF NOT EXISTS "gender" TEXT;

ALTER TABLE "attendees"
  ADD COLUMN IF NOT EXISTS "birthday" DATE,
  ADD COLUMN IF NOT EXISTS "gender" TEXT,
  ADD COLUMN IF NOT EXISTS "city" TEXT;
